"""Initial schema

Revision ID: 03eed8d28a8d
Revises: 
Create Date: 2026-05-25 17:40:16.211017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03eed8d28a8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price_ghs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_slug'), 'institutions', ['slug'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_table('student_directories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('faculty', sa.String(length=255), nullable=True),
    sa.Column('hall', sa.String(length=255), nullable=True),
    sa.Column('programme', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'phone', name='uq_institution_phone')
    )
    op.create_index('idx_students_department', 'student_directories', ['department'], unique=False)
    op.create_index('idx_students_faculty', 'student_directories', ['faculty'], unique=False)
    op.create_index('idx_students_gender', 'student_directories', ['gender'], unique=False)
    op.create_index('idx_students_hall', 'student_directories', ['hall'], unique=False)
    op.create_index('idx_students_institution', 'student_directories', ['institution_id'], unique=False)
    op.create_index('idx_students_level', 'student_directories', ['level'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sender_ids',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('sender_name', sa.String(length=11), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('arkesel_ref', sa.Text(), nullable=True),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id_ref', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id_ref'], ['sender_ids.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaigns_candidate', 'campaigns', ['candidate_id'], unique=False)
    op.create_table('campaign_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('arkesel_msg_id', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_directories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logs_campaign', 'campaign_logs', ['campaign_id'], unique=False)
    op.create_index('idx_logs_status', 'campaign_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_logs_status', table_name='campaign_logs')
    op.drop_index('idx_logs_campaign', table_name='campaign_logs')
    op.drop_table('campaign_logs')
    op.drop_index('idx_campaigns_candidate', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('sender_ids')
    op.drop_table('credit_transactions')
    op.drop_index('idx_students_level', table_name='student_directories')
    op.drop_index('idx_students_institution', table_name='student_directories')
    op.drop_index('idx_students_hall', table_name='student_directories')
    op.drop_index('idx_students_gender', table_name='student_directories')
    op.drop_index('idx_students_faculty', table_name='student_directories')
    op.drop_index('idx_students_department', table_name='student_directories')
    op.drop_table('student_directories')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_institutions_slug'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
