"""add google_id and make password nullable

Revision ID: 112df0a318f9
Revises: 03eed8d28a8d
Create Date: 2026-05-25 22:19:43.921293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112df0a318f9'
down_revision: Union[str, Sequence[str], None] = '03eed8d28a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('google_id', sa.String(), nullable=True))
    op.alter_column('candidates', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('uq_candidates_google_id', 'candidates', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candidates_google_id', 'candidates', type_='unique')
    op.alter_column('candidates', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('candidates', 'google_id')
    # ### end Alembic commands ###
