"""add index on credit_transactions.reference

Revision ID: 6190b28b163d
Revises: 112df0a318f9
Create Date: 2026-05-26 01:44:07.167065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6190b28b163d'
down_revision: Union[str, Sequence[str], None] = '112df0a318f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credit_transactions_reference'), 'credit_transactions', ['reference'], unique=False)
    op.drop_index(op.f('idx_students_hall'), table_name='student_directories')
    op.drop_column('student_directories', 'hall')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_directories', sa.Column('hall', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_students_hall'), 'student_directories', ['hall'], unique=False)
    op.drop_index(op.f('ix_credit_transactions_reference'), table_name='credit_transactions')
    # ### end Alembic commands ###
