"""add is_admin field to candidates

Revision ID: d0e7582dd9e2
Revises: 03eed8d28a8d
Create Date: 2026-05-25 22:15:53.268873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e7582dd9e2'
down_revision: Union[str, Sequence[str], None] = '03eed8d28a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Mark the existing admin account
    op.execute("UPDATE candidates SET is_admin = true WHERE email = 'admin@campusvoice.com'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'is_admin')
    # ### end Alembic commands ###
